name: Cleanup Preview Deployments
on:
  pull_request:
    types: [closed]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Remove Preview Deployment
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel remove --safe --yes "${{ github.event.pull_request.head.ref }}" --token=${{ secrets.VERCEL_TOKEN }} 